#!/bin/bash
gcc -g -Wall -Werror -Wextra -pedantic -std=c90 *.c -o monty
./monty pablo.m | cat -e
echo "
















"
valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./monty pablo.m
